export { calculateXirr } from './xirr'
export type { Cashflow } from './xirr'
export { buildXirrCashflows, toXirrCashflow, hasMinimumXirrPeriod, XIRR_OUTFLOW_TYPES, XIRR_INFLOW_TYPES, XIRR_MIN_DAYS } from './xirr-cashflows'
export type { XirrTxInput } from './xirr-cashflows'
export { calculateCostBasis, calculateQuantityHeld, calculateRealizedGain } from './cost-basis'
export { calculateNetDeposit } from './net-deposit'
export { calculateMarketValue, calculateSavingsBalance, calculateUnrealizedGain } from './current-value'
export { calculatePassiveIncome } from './passive-income'
export { calculateAllocation } from './allocation'
export type { AllocationSlice } from './allocation'
export {
  calculateGrossRentalYield,
  calculateNetRentalYield,
  calculateCashOnCash,
  calculateLtv,
  calculateEquity,
} from './real-estate'
export { calculateNetWorth } from './net-worth'
export { calculateTwr } from './twr'
export type { TwrPeriod } from './twr'
export { calculateAnnualReturn } from './annual-return'
export type { AnnualReturnFigures } from './annual-return'
export { calculateExcessReturn } from './benchmark'
export { buildNetWorthSeries } from './net-worth-series'
export type { NetWorthPoint } from './net-worth-series'
export { buildSimpleEntryMonthlySeries, buildSingleValueMonthlySeries } from './simple-entry-series'
export type { SimpleEntryRow, SimpleEntryMonthPoint, SingleValueRow, SingleValueMonthPoint } from './simple-entry-series'
export { annualizeAmount, calculateRecurringTotals } from './recurring-cashflow'
export type { RecurringFrequency, RecurringItemType, RecurringCashflowTotals } from './recurring-cashflow'
export { calculateOneTimeExpensesTotal } from './one-time-expenses'
export { calculatePercentChange } from './percent-change'
export { calculateSavingsRate } from './savings-rate'
export { calculateBufferMonths, classifyBufferMonths } from './buffer-coverage'
export type { BufferLabel } from './buffer-coverage'
export { calculatePassiveIncomeCoverage } from './passive-income-coverage'
export { determineFinancialHealthSignal } from './financial-health-signal'
export type { FinancialHealthSignal } from './financial-health-signal'
export { calculateMortgageAmortizationForYear } from './mortgage-amortization'
export type { MortgageType, MortgageTerms, AmortizationYearResult } from './mortgage-amortization'
export { calculateRentalPeriodCashflowForYear } from './rental-period-cashflow'
export type { RentalPeriodInput, RentalPeriodFrequency, RentalPeriodCashflowType, RentalPeriodYearTotals } from './rental-period-cashflow'
export { buildMonthlyCashflowSeries, lastNMonths } from './monthly-cashflow-series'
export type { RecurringItemHistoryInput, RecurringItemAmountPoint, OneTimeExpenseInput as MonthlyOneTimeExpenseInput, MonthlyCashflowPoint } from './monthly-cashflow-series'
export { calculateGoalProgress } from './goal-progress'
export type { GoalType, GoalProgressInput, GoalProgress } from './goal-progress'
